# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.srcs/sources_1/ip/vga_clock/vga_clock.xci
# IP: The module: 'vga_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.gen/sources_1/ip/vga_clock/vga_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.gen/sources_1/ip/vga_clock/vga_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.gen/sources_1/ip/vga_clock/vga_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.srcs/sources_1/ip/vga_clock/vga_clock.xci
# IP: The module: 'vga_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.gen/sources_1/ip/vga_clock/vga_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.gen/sources_1/ip/vga_clock/vga_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/joshu/OneDrive/Documents/College/ECE_580/final_project/final_project.gen/sources_1/ip/vga_clock/vga_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
